version: "{build}-{branch}"
skip_tags: true
shallow_clone: true
build: false
environment:
  global:
    # use a short path prefix to avoid running into path-length limitations
    STACK: stack --resolver lts-5 --skip-msys
    STACK_ROOT: C:\sr
  matrix:
  - DEPS:
  - DEPS: Win32-2.3.0.1
cache:
- "%STACK_ROOT%"
install:
- set PATH=%CD%\_stack;C:\msys64\usr\bin;%PATH%
  # might have to retry due to reliability issues with SourceForge
- sh tools/retry -n 32 pacman -S --needed --noconfirm autoconf automake tar
- sh tools/testscript prepare
test_script:
- sh tools/testscript build
